title: Goo Grotto Dev Log
description: >-
  notes and news from planet goopiter
url: "https://web.goo-grotto.com"
baseurl: ""

signup_url: "https://goo-grotto.com"

author:
  name: gen
  bluesky: https://bsky.app/profile/eclectech.bsky.social
  tumblr: https://www.tumblr.com/goo-grotto

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - .github
